### ISSUE TITLE
deploy issues

### ISSUE THREAD

**Issue by jiojio123** [cylab-tw/bluelight#1]
I tried to put the file in the browser's root directory，but  don't know how to run it.If click "start.html",it local html folder open.I use Orthanc .If i want to use bluelight in Orthanc ,where can i put it.

**Comment by birdeggb2777** [comment]
the config is In "bluelight/data/config.json".
If you want to specify the DICOMWeb server to your Orthanc, you should change the hostname, port from "orthanc.dicom.tw" to yours.
By the way, you need an HTTP server to launch BlueLight. Just click "start.html" will not work.

If you don't have an HTTP server, Suggest you can use "GitHub page" to create an HTTP server.

**Comment by jiojio123** [comment]
thank u  for your answer.
i use myeclipse and change target: "http://localhost:8080/start.html".but the function icon,such as "openfile.png"，don't display or click on the web page.
 if i can use local http server to launch Bluelight?

**Comment by cylien** [comment]
try: 
http://localhost:8080/bluelight/bluelight/html/start.html

Be sure the BlueLight should be in the root of the static HTTP path.

**Comment by jiojio123** [comment]
thank u for your help,I successfully deployed bluelight on local server.
i hope it can deploy on dcm4chee server.and i change “config.json”
（"AETitle": "DCM4CHEE",
      "enableHTTPS": true,
      "hostname": "localhost",
      "PORT": 8080,）and use "http://localhost:8080/bluelight/html/start.html"
But encount web error：“HTTP Status 404 - /bluelight/html/start.html”.How can i solve the problem,I look forward to u answer.

**Comment by cylien** [comment]
> （"AETitle": "DCM4CHEE",
> "enableHTTPS": true,
> "hostname": "localhost",
> "PORT": 8080,）and use "http://localhost:8080/bluelight/html/start.html"

this port is for the dicomweb server for DCH4CHEE, not for BlueLight.

> But encount web error：“HTTP Status 404 - /bluelight/html/start.html”.How can i solve the problem,I look forward to u answer.
try: 
http://localhost:8080/bluelight/bluelight/html/start.html

**Comment by jiojio123** [comment]
thank u for your help.
I've tried to use the "Live DEMO",but only "PT 0522c0001" success appear on BlueLight Viewer.The other picture report error
 "No 'Access-Control-Allow-Origin' header is present on the requested resource."
if the problem is  the connection of orthanc?

**Comment by cylien** [comment]
> 
> 
> thank u for your help.
> I've tried to use the "Live DEMO",but only "PT 0522c0001" success appear on BlueLight Viewer.The other picture report error
> "No 'Access-Control-Allow-Origin' header is present on the requested resource."
> if the problem is the connection of orthanc?
this error is coursed by the unusual deleting images on the Orthanc we installed. Because we did some experiments on the Orthanc that caused this error.  Currently, we have no time to re-install the Orthanc. Please try other images from the Orthanc.

**Comment by jiojio123** [comment]
I finally use Orthanc  as DICOMWeb Image Archive,but "BlueLight DICOMWeb Search" can't show the image List.The error "Access to XMLHttpRequest at 'http://202.195.86.167:8042/dicom-web/studies?PatientID=*' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." 
i think maybe orthanc password cause this problem.if i want to remote hosts  connect to the HTTP server,orthanc need to set the RegisteredUsers password.
Can I achieve remote access without a Orthanc password?

**Comment by cylien** [comment]
> I finally use Orthanc as DICOMWeb Image Archive,but "BlueLight DICOMWeb Search" can't show the image List.The error "Access to XMLHttpRequest at 'http://202.195.86.167:8042/dicom-web/studies?PatientID=*' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
> i think maybe orthanc password cause this problem.if i want to remote hosts connect to the HTTP server,orthanc need to set the RegisteredUsers password.

You need to add the CORS information in HTTP headers by Nginx, please refer to this link: https://book.orthanc-server.com/faq/nginx.html

> Can I achieve remote access without a Orthanc password?

you have to disable the authentication option in the config file of Orthanc

**Comment by jiojio123** [comment]
thank u for your help.
i want to link dcm4chee server,but the reture json value are out of oreder  .whether i need to change "onloadsome.js" file.
i don't konw how to change the configuration，i hope to  your help 😂

**Comment by cylien** [comment]
> i want to link dcm4chee server,but the reture json value are out of order .

You can get the JSON arrays, and then sort them by specified attribute such as StudyDate, PatientID, etc., in the front-end by using JavaScript, e.g., https://www.c-sharpcorner.com/UploadFile/fc34aa/sort-json-object-array-based-on-a-key-attribute-in-javascrip/

**Comment by jiojio123** [comment]
I successfully deployed bluelight on dcm4chee with your help. But when I downloaded the DCM file with DCM4Chee Wado , it can't be opened in bluelight .What is the reason for this ？

**Comment by cylien** [comment]
> I successfully deployed bluelight on dcm4chee with your help. But when I downloaded the DCM file with DCM4Chee Wado , it can't be opened in bluelight .What is the reason for this ？

Currently, BlueLight uses the WADO-URI to retrieve DICOM object from dcm4chee. 
Please change the  WADO API in config.json to like follows : 

  "AETitle": "DCM4CHEE",
  "QIDO": "aets/DCM4CHEE/rs",
  "WADO": " aets/DCM4CHEE/wado",

**Comment by jiojio123** [comment]
thank u. 
i  change the config.json according to your method,but DICOM file still can't be opened in bluelight. Anything else that needs to be modified?

**Comment by jiojio123** [comment]
thank u.
i change the config.json according to your method,but DICOM file still can't be opened in bluelight. Anything else that needs to be modified?
I use DCM4CHEE ARC 5.13.0，is it a version problem？

**Comment by cylien** [comment]
> 
> 
> thank u.
> i change the config.json according to your method,but DICOM file still can't be opened in bluelight. Anything else that needs 

You can drag and drop the DICOM file on the BlueLight to ensure that the DICOM file can open by BlueLight. 
Here is an online link to open the local DCOM file by BlueLight: https://bl.dicom.tw




> I use DCM4CHEE ARC 5.13.0，is it a version problem？

No, be sure that the DICOMweb Service of DCM4CHEE is active.
