### ISSUE TITLE
oauth2 support

### ISSUE THREAD

**Issue by DraconPern** [cylab-tw/bluelight#12]
Please add oauth2 or openid connect support to the development roadmap.  It's important in real world deployments.  Currently I use ohif viewer and it has support for it.

**Comment by cylien** [comment]
Thank you for your input. The feature of the oauth2 client has been implemented in [Raccoon](https://github.com/cylab-tw/raccoon). I have put this issue into our to-do list of BlueLight.

**Comment by cylien** [comment]
b3541c0766039de6df6eb9ef72f54b19653cf8f5
