### ISSUE TITLE
Parameter Json

### ISSUE THREAD

**Issue by bmkimagem** [cylab-tw/bluelight#2]
Congratulations, very good. You can pass the information through a json for example. So you could open DICOM images stored on Amazon S3 for example.

**Comment by cylien** [comment]
Just click the icon of "open file", type the URL of storing DICOM on Amazon.

**Comment by bmkimagem** [comment]
So it worked well. But I would like to automate. For example, from my RIS click on the patient and load the image in your direct application. For that, the open file would not work. You would need to pass the address through a variable for your application.
Do you have any tips on how I can do this?

**Comment by bmkimagem** [comment]
I managed to solve it. I disabled Open File and created a json with an array with all the addresses in the S3 bucket.

**Comment by bmkimagem** [comment]
I managed to solve it. I disabled Open File and created a json with an array with all the addresses in the S3 bucket.
Thanks
I will end this.
