### ISSUE TITLE
Frontal and Saggital view

### ISSUE THREAD

**Issue by cmylmz0** [cylab-tw/bluelight#32]
Hi @cylien and @birdeggb2777, 

Currently, we see axial on the main screen. How can we convert this to frontal or saggital?

Thank you.

**Comment by cylien** [comment]
There is a 3D MPR plugin to deal with it. Please watch the following demo video. 
https://youtu.be/UkZt_Qbw1Rk?t=341
 
#31 - 2D MPR is still developing; the prototype is shown below.

![ezgif-5-d28f34d78a](https://github.com/cylab-tw/bluelight/assets/3929275/093f9c7c-57e0-4461-9cce-c439ef11806a)

**Comment by cylien** [comment]
Added it.
177c612
bce65ce

**Comment by cylien** [comment]
duplicate with #31 
177c612
bce65ce
