### ISSUE TITLE
Open on remote server

### ISSUE THREAD

**Issue by threehappypenguins** [cylab-tw/bluelight#37]
Is there any way to open data located on the server running bluelight? And to ensure that the user can't browse around the server and only the specific folder (and sub folders) with the data?

**Comment by cylien** [comment]
The live demo of Bluelight connected with a public [Raccoon](https://raccoon.dicom.org.tw/) which is a DIOCMweb server.
* The live demo URL for bluelight: https://cylab-tw.github.io/bluelight/search/html/start.html

You can use the search page of Bluelight to query/retrieve a DICOMweb server with the levels of study-series-Instance hierarchically.  

By the way, drag a folder in a local disk to Bluelight, which can display all images in the folder.

![ezgif-5-3f087daef1](https://github.com/cylab-tw/bluelight/assets/3929275/c79500fb-c55a-4b8c-b657-59563825f225)
](url)
