### ISSUE TITLE
Configuration for local files?

### ISSUE THREAD

**Issue by gsaielli** [cylab-tw/bluelight#5]
Where do we configure Bluelight to load local files?

**Comment by cylien** [comment]
Just drag and drop files or folders to BlueLight. There is no need to configure it.
Also, there is an icon for opening local files in the first left position on the top menu.

**Comment by gsaielli** [comment]
By local I mean the same webserver where blue is hosted. Can we view DICOM images hosted in the same server? How?
BTW if there is no need to configure, what's the point of the data/config.json file?

Thanks.

**Comment by cylien** [comment]
> Can we view DICOM images hosted in the same server? How?  BTW if there is no need to configure, what's the point of the data/config.json file?
The data/config.json is used for configuring the connection for DICOMWeb Servers such as Orthanc, DCM4CHEE, etc.  BL is hosted in a web server can be a role of ''bridge' to connect to any DIOCMWeb server.

**Comment by gsaielli** [comment]
Well I was unable to connect to my local Orthanc and still wondering if i can use LOCAL DICOM folders, instead of having to upload each time.
