### ISSUE TITLE
Reduce QIDO requests in Search page

### ISSUE THREAD

**Issue by cylien** [cylab-tw/bluelight#6]
Using DICOM-Study-Series-Image heretically search to replace the current method. The current method sends a QIDO Study level query and then sends too many QIDO-RS series/instance queries to cause the search page slow.
while clicking the search button, send a QIDO Study Level query. If the user clicks the study, then launch the QIDO series/instance level query to avoid sending all QIDO requests of studies.

**Comment by cylien** [comment]
0f96f8b97bc971ccf5e087efcad86342d49362f4

**Comment by cylien** [comment]
0f96f8b97bc971ccf5e087efcad86342d49362f4

**Comment by cylien** [comment]
0f96f8b97bc971ccf5e087efcad86342d49362f4

**Comment by birdeggb2777** [comment]
Fix #6

**Comment by birdeggb2777** [comment]
fixed #6

**Comment by birdeggb2777** [comment]
Fixes #6
